<?php

namespace Tests\Unit;

use Tests\TestCase;
use App\Models\User;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\RefreshDatabase;

class UserTest extends TestCase
{
    use RefreshDatabase, DatabaseMigrations;

    public function test_get_all_members()
    {
        User::factory()->count(3)->create(['role' => 0]);

        $response = $this->getJson('/api/member');

        $response->assertStatus(200)
            ->assertJsonStructure([
                'data' => [
                    '*' => [
                        'id',
                        'name',
                        'email',
                        'avatar',
                        'phone',
                        'address',
                        'fullname',
                        'created_at',
                        'updated_at',
                        'role',
                    ],
                ],
            ]);

        $this->assertCount(3, $response->json('data'));

        // Update the expected name based on the actual data generated by the factory
        $expectedName = User::first()->name;

        $response->assertJson([
            'data' => [
                [
                    'name' => $expectedName,
                    // Add other expected details
                ],
            ],
        ]);
    }
}
